### PR TITLE
Add Virt SIG qemu-kvm-ev repo (RHBZ#1367696)

### PR DESCRIPTION
**Pull request by hguemar**
Renamed Virt SIG repositories to avoid conflict when you install
centos-release-qemu-ev from CentOS extras.

### CODE REVIEW

**Comment by apevec** [comment]
For now -1 for adding this to Mitaka, @dmsimard has this as a topic for Aug 24 RDO meeting https://etherpad.openstack.org/p/RDO-Meeting
Proposal would be to add this in rdo-release >= newton only.

**Comment by hguemar** [comment]
Works for me.

**Comment by apevec** [comment]
@hguemar please rebase it to newton branch

**Comment by hguemar** [comment]
Replaced by #7

**Pull request closed without merging**
